### ISSUE TITLE
✨ Add Full Journey for Outside Collaborators

### ISSUE THREAD

**Issue by connormaglynn** [ministryofjustice/operations-engineering-join-github#31]
**User Need**

**As a** outside collaborator
**I want** to quickly get access to GitHub
**so that** I can start my work

**Value**

Enable outside collaborators to quickly find the relevant place to get their access

**Functional Requirements:**

- If the user inputted email is not in the allow list, redirect the user to a page about outside collaborators with the relevant links
- Defined list of allowed email domains implemented

**Non-Functional Requirements:**

- Simple for a user to complete the process

**Acceptance Criteria:**

- [x] When user provides an email domain that is not in the allowed list, the user is redirected to a page that details Outside Collaborators / Asking for help

**Notes:**

- Outside collaborators are onboarded via github-outside-collaborators and github-collaborators

**Comment by jasonBirchall** [comment]
Journey complete and deployed to dev.
