### ISSUE TITLE
🏗️ Create Cloud Platform Namespace For a Production Environment

### ISSUE THREAD

**Issue by connormaglynn** [ministryofjustice/operations-engineering-join-github#36]
**User Need**

**As a** Developer
**I want** a production environment
**so that** I can deploy my service live

**Value**

Segregated environment for production to reduce the risk of failure

**Functional Requirements:**

1. We have the infrastructure to run production workloads (this will be a cloud platform namespace)

**Non-Functional Requirements:**

1. Namespace follows standard naming conventions

**Acceptance Criteria:**

- [x] Cloud Platform namespace created called `operations-engineering-join-github-prod`
- [x] Rename the dev environment to `operations-engineering-join-github-dev`

**Notes:**

-

**Comment by jasonBirchall** [comment]
Rename will be difficult - we will need to recreate. Saying that, recreating takes no time at all.

**Comment by jasonBirchall** [comment]
https://github.com/ministryofjustice/cloud-platform-environments/pull/18565

**Comment by jasonBirchall** [comment]
Production environment: `operations-engineering-join-github-prod`
Development environment: `operations-engineering-join-github-dev`
